In [40]:
import numpy as np
import exact_cover as ec
RAW_SHAPES = {
    "F": np.array([[1, 1, 0], [0, 1, 1], [0, 1, 0]]),
    "I": np.array([[1, 1, 1, 1, 1]]),
    "L": np.array([[1, 0, 0, 0], [1, 1, 1, 1]]),
    "N": np.array([[1, 1, 0, 0], [0, 1, 1, 1]]),
    "P": np.array([[1, 1, 1], [1, 1, 0]]),
    "T": np.array([[1, 1, 1], [0, 1, 0], [0, 1, 0]]),
    "U": np.array([[1, 1, 1], [1, 0, 1]]),
    "V": np.array([[1, 1, 1], [1, 0, 0], [1, 0, 0]]),
    "W": np.array([[1, 0, 0], [1, 1, 0], [0, 1, 1]]),
    "X": np.array([[0, 1, 0], [1, 1, 1], [0, 1, 0]]),
    "Y": np.array([[0, 1, 0, 0], [1, 1, 1, 1]]),
    "Z": np.array([[1, 1, 0], [0, 1, 0], [0, 1, 1]])
}

def nombre_de_symetries(d, nb_rotations):
    nouvelles_lettres = {}
    for j, lettre_initiale in d.items():
        symetries = []
        for _ in range(nb_rotations):
            symetries.append(lettre_initiale)
            symetries.append(np.transpose(lettre_initiale))
            lettre_initiale = np.rot90(lettre_initiale)
        nouvelles_lettres[j] = symetries
    return nouvelles_lettres
            

def traductions(dictionnaire, n, p):
    dico_positions = {}
    for lettre, liste_symetries in dictionnaire.items():
        dico_positions[lettre] = []
        for sym in liste_symetries:
            h, l = sym.shape
            for k in range(n - h + 1):
                for z in range(p - l + 1):
                    cadre = np.zeros((n, p))
                    for i in range(h):
                        for j in range(l):
                            cadre[k + i][z + j] = sym[i][j]
                    dico_positions[lettre].append(np.ravel(cadre))
    return dico_positions


        

In [42]:
dico = nombre_de_symetries(RAW_SHAPES,4)
out = traductions(dico,12,5)

toto = []

translator = {}
nkeys = len(out.keys())
counter = 0
for key in out.keys():
    tmp = [0]*nkeys
    tmp[counter] = 1
    translator[key] = tmp 
    counter += 1

for key, value in out.items():
    for row in value:
        toto.append( translator[key] + row.tolist() )

matrice_finale = np.array(toto).astype(int)
print(matrice_finale)


LE_RESULTAT = get_exact_cover(matrice_finale)

[[1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 1 1 0]]


NameError: name 'get_exact_cover' is not defined